---
sidebar: sidebar
permalink: config-mirrornotmultipath-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: config.mirrornotmultipath events
---

= config.mirrornotmultipath events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
config.mirrornotmultipath events are reported when a disk is not multipathed but synchronous mirroring is enabled, and corrective actions typically involve following the documented corrective action guidance.

== config.MirrorNotMultiPath
*Severity*::
ERROR
*Description*::
This message occurs when a disk is not multipathed but synchronous mirroring is enabled.
*Corrective Action*::
Multipath the disk shelf stack by also attaching it to a different host adapter via the other shelf module in each disk shelf in the stack.
*Syslog Message*::
Disk %s and other disks on this loop/domain are not multipathed and should be for synchronous mirroring configuration.
*Parameters*::
*disk* (STRING): Name of the disk.
