---
sidebar: sidebar
permalink: dcn-callhome-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: dcn.callhome events
---

= dcn.callhome events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
dcn.callhome EMS events occur when ONTAP encounters issues associated with AutoSupport invocation on the data compute node (DCN).

== dcn.callhome.invoke
*Severity*::
NOTICE
*Description*::
This message occurs when you invoke an AutoSupport(R) message on the data compute node (DCN), and the "type" of that message is set to "test". This message contains very little content and is intended for testing AutoSupport(R) end-to-end. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for %s on DCN: %s
*Parameters*::
*subject* (STRING): DCN AutoSupport subject or title for this event.
*dcn_node_name* (STRING): Data compute node name.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
*URI* (STRING): Alternate destination for this ASUP. If this is set, this ASUP is delivered to this alternate destination.

== dcn.callhome.invoke.all
*Severity*::
NOTICE
*Description*::
This message occurs when you invoke an AutoSupport(R) message on the data compute node (DCN), and the "type" of that message is set to "all". For the benefit of technical support, the message also contains troubleshooting content, which might lengthen the collection time required. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for %s on DCN: %s
*Parameters*::
*subject* (STRING): DCN AutoSupport subject or title for this event.
*dcn_node_name* (STRING): Data compute node name.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
*URI* (STRING): Alternate destination for this ASUP. If this is set, this ASUP is delivered to this alternate destination.

== dcn.callhome.management.log
*Severity*::
NOTICE
*Description*::
This message occurs when the MANAGEMENT_LOG AutoSupport or 'call home' event is sent for the data compute node (DCN). This message occurs on a daily basis and is sent from the DCN only. Information is sent to NetApp technical support to ensure that subsequent communications work and to enable operations analysis. Some results of these analysis might include recommendations on upgrades, firmware changes, and configuration changes to improve the reliability and performance of the node. If your node is configured to do so it generates and transmits an AutoSupport (or 'call home') to NetApp technical support and to the configured destinations on a daily basis. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for %s on DCN: %s
*Parameters*::
*subject* (STRING): DCN AutoSupport subject or title for this event.
*dcn_node_name* (STRING): Data compute node name.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.

== dcn.callhome.weekly
*Severity*::
NOTICE
*Description*::
This message occurs when the weekly AutoSupport or 'call home' event is sent for the data compute node (DCN). Information is sent to NetApp technical support to ensure that subsequent communications work and to enable operations analysis. Some results of these analysis might include recommendations on upgrades, firmware changes, and configuration changes to improve the reliability and performance of the system. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for %s on DCN: %s
*Parameters*::
*subject* (STRING): DCN AutoSupport subject or title for this event.
*dcn_node_name* (STRING): Data compute node name.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
