---
sidebar: sidebar
permalink: de-callhome-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: de.callhome events
---

= de.callhome events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
Learn about de.callhome EMS events for invoke all performance activity.

== de.callhome.invoke
*Severity*::
NOTICE
*Description*::
This message occurs when you invoke an AutoSupport(R) message on the AI Data Engine, and the "type" of that message is set to "test". This message contains very little content and is intended for testing AutoSupport(R) end-to-end. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for AI Data Engine: %s
*Parameters*::
*subject* (STRING): AI Data Engine AutoSupport subject or title for this event.
*de_uuid* (STRING): AI Data Engine UUID.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
*URI* (STRING): Alternate destination for this ASUP. If this is set, this ASUP is delivered to this alternate destination.

== de.callhome.invoke.all
*Severity*::
NOTICE
*Description*::
This message occurs when you invoke an AutoSupport(R) message on the AI Data Engine, and the "type" of that message is set to "all". For the benefit of technical support, the message also contains troubleshooting content, which might lengthen the collection time required. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for AI Data Engine: %s
*Parameters*::
*subject* (STRING): AI Data Engine AutoSupport subject or title for this event.
*de_uuid* (STRING): AI Data Engine UUID.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
*URI* (STRING): Alternate destination for this ASUP. If this is set, this ASUP is delivered to this alternate destination.

== de.callhome.management.log
*Severity*::
NOTICE
*Description*::
This message occurs when the MANAGEMENT_LOG AutoSupport or 'call home' event is sent for the AI Data Engine. This message occurs on a daily basis and is sent from the AI Data Engine only. Information is sent to NetApp technical support to ensure that subsequent communications work and to enable operations analysis. Some results of these analysis might include recommendations on upgrades, firmware changes, and configuration changes to improve the reliability and performance of the node. If your node is configured to do so it generates and transmits an AutoSupport (or 'call home') to NetApp technical support and to the configured destinations on a daily basis. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for AI Data Engine MANAGEMENT_LOG
*Parameters*::
*subject* (STRING): AI Data Engine AutoSupport subject or title for this event.
*de_uuid* (STRING): AI Data Engine UUID.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.

== de.callhome.performance.data
*Severity*::
NOTICE
*Description*::
This message occurs when the Performance Data AutoSupport or 'call home' event is sent for the AI Data Engine. Information is sent to NetApp technical support to ensure that subsequent communications work and to enable operations analysis. Some results of these analysis might include recommendations on upgrades, firmware changes, and configuration changes to improve the reliability and performance of the system. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for AI Data Engine PERFORMANCE DATA
*Parameters*::
*subject* (STRING): AI Data Engine AutoSupport subject or title for this event.
*de_uuid* (STRING): AI Data Engine UUID.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.

== de.callhome.performance.snap
*Severity*::
NOTICE
*Description*::
This message occurs when you invoke an AutoSupport(R) message on the AI Data Engine, and the "type" of that message is set to "performance". This message contains the performance snapshot of the AI Data Engine. Information is sent to NetApp technical support to ensure that subsequent communications work and to enable operations analysis. Some results of these analysis might include recommendations on upgrades, firmware changes, and configuration changes to improve the reliability and performance of the system. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for AI Data Engine PERFORMANCE SNAPSHOT
*Parameters*::
*subject* (STRING): AI Data Engine AutoSupport subject or title for this event.
*de_uuid* (STRING): AI Data Engine UUID.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
*URI* (STRING): Alternate destination for this ASUP. If this is set, this ASUP is delivered to this alternate destination.

== de.callhome.weekly
*Severity*::
NOTICE
*Description*::
This message occurs when the weekly AutoSupport or 'call home' event is sent for the AI Data Engine. Information is sent to NetApp technical support to ensure that subsequent communications work and to enable operations analysis. Some results of these analysis might include recommendations on upgrades, firmware changes, and configuration changes to improve the reliability and performance of the system. If your system is configured to do so, it generates and transmits an AutoSupport (or 'call home') message to NetApp technical support and to the configured destinations. Successful delivery of an AutoSupport message significantly improves problem determination and resolution.
*Corrective Action*::
(None).
*Syslog Message*::
Call home for AI Data Engine WEEKLY_LOG
*Parameters*::
*subject* (STRING): AI Data Engine AutoSupport subject or title for this event.
*de_uuid* (STRING): AI Data Engine UUID.
*payload_path* (STRING): Path to the ASUP payload in the shared directory.
*sequence* (LONGINT): Sequence number to use to generate this AutoSupport. Use the value "0" to auto-generate the next AutoSupport sequence number.
*dcn_sequence* (LONGINT): DCN sequence number.
