---
sidebar: sidebar
permalink: nblade-cifsetcdmaxtxnlimit-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: nblade.cifsetcdmaxtxnlimit events
---

= nblade.cifsetcdmaxtxnlimit events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
nblade.cifsetcdmaxtxnlimit events are reported when the number of Access Control Entries (ACE) present in an MSRPC request for updating share permissions exceeds the supported maximum etcd limit of 1,022 entries, and corrective actions typically involve following the documented corrective action guidance.

== Nblade.cifsEtcdMaxTxnLimit
*Severity*::
ERROR
*Description*::
This message occurs when the number of Access Control Entries (ACE) present in an MSRPC request for updating share permissions exceeds the supported maximum etcd limit of 1,022 entries.
*Corrective Action*::
Retry the operation with less than the maximum supported number of ACEs in the MSRPC request.
*Syslog Message*::
Received an etcd failure event. Message is %s.
*Parameters*::
*pMessage* (STRING): Description of the error.
