---
sidebar: sidebar
permalink: vfilermigrate-diskownershipmismatch-events.html
keywords: ems, message, messages, event, events, group, catalog
summary: vfilermigrate.diskownershipmismatch events
---

= vfilermigrate.diskownershipmismatch events
:toc: macro
:toclevels: 1
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
vfilermigrate.diskownershipmismatch events are reported when the SnapMover feature is licensed but the disk ownership model is not using the software-based disk ownership model, and corrective actions typically involve following the documented corrective action guidance.

== vfilermigrate.diskOwnershipMismatch
*Severity*::
ERROR
*Description*::
The SnapMover feature is licensed but the disk ownership model is not using the software-based disk ownership model.
*Corrective Action*::
Boot the filer into maintenance mode and use the 'disk assign' or 'disk upgrade_ownership' command to assign disk ownership.
*Syslog Message*::
SnapMover is licensed but the system is not using software-based disk ownership.
*Parameters*::
(None).
